spring:
  application:
    name: inventoryms
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      
server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true


management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    io.github.resilience4j: debug

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 8
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowType: COUNT_BASED
        waitDurationInOpenState: 30
        failureRateThreshold: 50
        minimumNumberOfCalls: 4
    instances:
      inventorymsClient:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransferFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 20s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED